export const RestAPIActionTypes = {
    // Request and Response Actions
    SET_REQUEST: 'SET_REQUEST',
    SET_RESPONSE: 'SET_RESPONSE',
    SET_REQUEST_NAME: 'SET_REQUEST_NAME',
    SAVE_REQUEST: 'SAVE_REQUEST',
    // Request Configuration Actions
    SET_URL: 'SET_URL',
    SET_METHOD: 'SET_METHOD',
    SET_HEADERS: 'SET_HEADERS',
    SET_BODY: 'SET_BODY',
    SET_PARAMS: 'SET_PARAMS',

    // History Management Actions
    ADD_TO_HISTORY: 'ADD_TO_HISTORY', // Add a request to history
    CLEAR_HISTORY: 'CLEAR_HISTORY',     // Clear the history

    //Authentication Actions
    SET_AUTH_TYPE: 'SET_AUTH_TYPE',
    //Basic Auth Actions
    SET_BASIC_AUTH_USERNAME: 'SET_BASIC_AUTH_USERNAME',
    SET_BASIC_AUTH_PASSWORD: 'SET_BASIC_AUTH_PASSWORD',
    //Bearer Token Actions
    SET_BEARER_TOKEN_TOKEN: 'SET_BEARER_TOKEN_TOKEN',
    //JWT BEARER Actions
    SET_JWT_BEARER_ALGORITHM: 'SET_JWT_BEARER_ALGORITHM',
    SET_JWT_BEARER_SECRET: 'SET_JWT_BEARER_SECRET',
    SET_JWT_BEARER_SECRET_BASE64_ENCODED: 'SET_JWT_BEARER_SECRET_BASE64_ENCODED',
    SET_JWT_BEARER_PAYLOAD: 'SET_JWT_BEARER_PAYLOAD',
    SET_JWT_BEARER_REQUEST_HEADER_PREFIX: 'SET_JWT_BEARER_REQUEST_HEADER_PREFIX',
    SET_JWT_BEARER_JWT_HEADERS:
    'SET_JWT_BEARER_JWT_HEADERS',
    SET_JWT_BEARER_ADD_JWT_TOKEN_TO: 'SET_JWT_BEARER_ADD_JWT_TOKEN_TO',
    //OAuth 1.0 Actions
    SET_AUTH_ONE_SIGNATURE_METHOD: 'SET_AUTH_ONE_SIGNATURE_METHOD',
    SET_AUTH_ONE_CONSUMER_KEY: 'SET_AUTH_ONE_CONSUMER_KEY',
    SET_AUTH_ONE_CONSUMER_SECRET: 'SET_AUTH_ONE_CONSUMER_SECRET',
    SET_AUTH_ONE_ACCESS_TOKEN:
    'SET_AUTH_ONE_ACCESS_TOKEN',
    SET_AUTH_ONE_TOKEN_SECRET: 'SET_AUTH_ONE_TOKEN_SECRET',
    SET_AUTH_ONE_CALLBACK_URL: 'SET_AUTH_ONE_CALLBACK_URL',
    SET_AUTH_ONE_VERIFIER: 'SET_AUTH_ONE_VERIFIER',
    SET_AUTH_ONE_TIMESTAMP: 'SET_AUTH_ONE_TIMESTAMP',
    SET_AUTH_ONE_NONCE: 
    'SET_AUTH_ONE_NONCE',
    SET_AUTH_ONE_REALM: 
    'SET_AUTH_ONE_REALM',
    SET_AUTH_ONE_VERSION: 'SET_AUTH_ONE_VERSION',
    SET_AUTH_ONE_INCLUDE_BODY_HASH: 'SET_AUTH_ONE_INCLUDE_BODY_HASH',
    SET_AUTH_ONE_ADD_EMPTY_PARAMETERS_TO_SIGNATURE: 'SET_AUTH_ONE_ADD_EMPTY_PARAMETERS_TO_SIGNATURE',
    SET_AUTH_ONE_ADD_AUTHORIZATION_DATA_TO: 'SET_AUTH_ONE_ADD_AUTHORIZATION_DATA_TO',
    //OAuth 2.0 Actions
    SET_AUTH_TWO_AVAILABLE_TOKENS: 'SET_AUTH_TWO_AVAILABLE_TOKENS',
    SET_AUTH_TWO_TOKEN: 'SET_AUTH_TWO_TOKEN',
    SET_AUTH_TWO_HEADER_PREFIX: 'SET_AUTH_TWO_HEADER_PREFIX',
    SET_AUTH_TWO_AUTO_REFRESH_TOKEN: 'SET_AUTH_TWO_AUTO_REFRESH_TOKEN',
    SET_AUTH_TWO_SHARE_TOKEN:
    'SET_AUTH_TWO_SHARE_TOKEN',
    SET_AUTH_TWO_TOKEN_NAME: 'SET_AUTH_TWO_TOKEN_NAME',
    SET_AUTH_TWO_GRANT_TYPE: 'SET_AUTH_TWO_GRANT_TYPE',
    SET_AUTH_TWO_CALLBACK_URL: 'SET_AUTH_TWO_CALLBACK_URL',
    SET_AUTH_TWO_AUTHORIZE_USING_BROWSER: 'SET_AUTH_TWO_AUTHORIZE_USING_BROWSER',
    SET_AUTH_TWO_AUTH_URL: 'SET_AUTH_TWO_AUTH_URL',
    SET_AUTH_TWO_ACCESS_TOKEN_URL: 'SET_AUTH_TWO_ACCESS_TOKEN_URL',
    SET_AUTH_TWO_CLIENT_ID: 'SET_AUTH_TWO_CLIENT_ID',
    SET_AUTH_TWO_CLIENT_SECRET: 'SET_AUTH_TWO_CLIENT_SECRET',
    SET_AUTH_TWO_SCOPE: 'SET_AUTH_TWO_SCOPE',
    SET_AUTH_TWO_STATE: 'SET_AUTH_TWO_STATE',
    SET_AUTH_TWO_CLIENT_AUTHENTICATION: 'SET_AUTH_TWO_CLIENT_AUTHENTICATION',
    SET_AUTH_TWO_REFRESH_TOKEN_URL: 'SET_AUTH_TWO_REFRESH_TOKEN_URL',
    SET_AUTH_TWO_AUTH_REQUEST: 'SET_AUTH_TWO_AUTH_REQUEST',
    SET_AUTH_TWO_TOKEN_REQUEST: 'SET_AUTH_TWO_TOKEN_REQUEST',
    SET_AUTH_TWO_REFRESH_REQUEST: 'SET_AUTH_TWO_REFRESH_REQUEST',
    CLEAR_AUTH_TWO_COOKIES: 'CLEAR_AUTH_TWO_COOKIES',
    GET_AUTH_TWO_NEW_ACCESS_TOKEN:
    'GET_AUTH_TWO_NEW_ACCESS_TOKEN',
    //API Key Actions
    SET_API_KEY_KEY: 
    'SET_API_KEY_KEY',
    SET_API_KEY_VALUE: 'SET_API_KEY_VALUE',
    SET_API_KEY_ADD_TO: 'SET_API_KEY_ADD_TO',
};